groups:
- name: concourse
  jobs:
  - atc
  - blackbox
  - deploy
  - fly
  - baggageclaim
  - jettison
  - tsa
  - major
  - minor
  - patch
  - rc
  - shipit
  - testflight

- name: publish
  jobs:
  - aws-box
  - github-release
  - hangar
  - product
  - publish-houdini
  - push-departures
  - push-docs
  - virtualbox-box

- name: bosh-lite
  jobs: [provision, teardown]

- name: rubbish-bin
  jobs:
  - master-merge
  - unfudge
  - tracksuit

jobs:
- name: fly
  public: true
  plan:
  - get: concourse
    trigger: true
  - aggregate:
    - task: linux
      file: concourse/ci/fly-linux.yml
    - task: darwin
      file: concourse/ci/fly-darwin.yml
    - task: windows
      file: concourse/ci/fly-windows.yml

- name: atc
  public: true
  plan:
  - get: concourse
    trigger: true
  - aggregate:
    - task: go-unit
      file: concourse/ci/atc-go.yml
    - task: js-unit
      file: concourse/ci/atc-js.yml

- name: baggageclaim
  public: true
  serial: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    privileged: true
    file: concourse/ci/baggageclaim.yml

- name: blackbox
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/blackbox.yml

- name: jettison
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/jettison.yml

- name: tsa
  public: true
  plan:
  - get: concourse
    trigger: true
  - task: build
    file: concourse/ci/tsa.yml

- name: rc
  public: true
  serial_groups: [version]
  plan:
  - get: concourse
    trigger: true
    passed: [atc, fly, blackbox, tsa, jettison, baggageclaim]
  - get: version
    params: {pre: rc}
  - task: create-candidate-release
    file: concourse/ci/create-candidate-release.yml
  - put: candidate-release
    params: {from: create-candidate-release/concourse-(.*).tgz}
  - put: version
    params: {file: version/number}

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: concourse
    passed: [shipit]
    params: {submodules: none}
    trigger: true
  - get: version
    passed: [shipit]
    params: {bump: patch}
    trigger: true
  - put: version
    params: {file: version/number}

- name: provision
  serial: true
  plan:
  - get: deployments
  - get: bosh-lite
  - task: provision
    file: deployments/lite/ci/provision-bosh-lite.yml
  - put: bosh-lites
    params:
      add: provision/lock

- name: teardown
  serial: true
  plan:
  - put: bosh-lites
    params: {acquire: true}
  - do:
    - get: deployments
    - task: teardown
      file: deployments/lite/ci/teardown-bosh-lite.yml
    on_success:
      put: bosh-lites
      params: {remove: bosh-lites}
    on_failure:
      put: bosh-lites
      params: {release: bosh-lites}

- name: testflight
  public: true
  serial: true
  plan:
  - put: bosh-lites
    params: {acquire: true}
  - do:
    - aggregate:
      - get: concourse
        passed: [rc]
        trigger: true
      - get: candidate-release
        passed: [rc]
        trigger: true
      - get: version
        passed: [rc]
        trigger: true
      - get: garden-linux-release
        trigger: true
        resource: garden-linux
      - get: lite-stemcell
    - put: lite-deployment
      params:
        target_file: bosh-lites/metadata
        manifest: concourse/src/github.com/concourse/testflight/deployment.yml
        stemcells: [lite-stemcell/*.tgz]
        releases:
          - garden-linux-release/*.tgz
          - candidate-release/concourse-*.tgz
    - task: build
      privileged: true
      file: concourse/ci/testflight.yml
    ensure:
      put: bosh-lites
      params: {release: bosh-lites}

- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: concourse
      params: {submodules: none}
      passed: [testflight]
      trigger: true
    - get: candidate-release
      passed: [testflight]
      trigger: true
    - get: version
      passed: [testflight]
      trigger: true
    - get: garden-linux-release
      resource: garden-linux
      passed: [testflight]
      trigger: true
    - get: turbulence
    - get: bosh-stemcell
      resource: aws-stemcell
    - get: deployments
      trigger: true
  - put: aws-deployment
    params:
      manifest: deployments/ci/deployments/concourse.yml
      stemcells: [bosh-stemcell/*.tgz]
      releases:
        - garden-linux-release/*.tgz
        - candidate-release/concourse-*.tgz
        - turbulence/*.tgz
  - put: tracker
    params: {repos: [concourse]}

- name: unfudge
  plan:
  - get: bosh-lites
  - put: bosh-lites
    params: {release: bosh-lites}

- name: shipit
  serial_groups: [version]
  plan:
  - aggregate:
    - get: concourse
      passed: [deploy]
      params: {submodules: none, fetch: [master]}
    - get: candidate-release
      passed: [deploy]
    - get: version
      passed: [deploy]
      params: {bump: final}
    - get: garden-linux-release
      passed: [deploy]
      resource: garden-linux
    - get: deployments
  - task: finalize-release
    file: concourse/ci/finalize-release.yml
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: concourse-master
      params:
        repository: finalize-release/concourse
        tag: version/number
        tag_prefix: v
    - put: final-release
      params: {from: finalize-release/concourse-(.*).tgz}

- name: virtualbox-box
  public: true
  serial: true
  plan:
  - aggregate:
    - get: final-release
      passed: [shipit]
      trigger: true
    - get: garden-linux-release
      passed: [shipit]
      resource: garden-linux
      trigger: true
    - get: concourse
      params: {submodules: none}
      passed: [shipit]
      trigger: true
    - get: concourse-lite
    - get: deployments
  - task: build-box
    privileged: true
    file: deployments/buildbox/ci/build-boxes.yml
  - put: virtualbox-box
    params: {from: build-box/concourse-lite/concourse-virtualbox-ubuntu-trusty-(.*).box}
  - task: build-release-notes
    file: concourse/ci/build-release-notes.yml
  - put: virtualbox-box-cloud
    params:
      description: build-release-notes/notes.md
      release: true
      url: virtualbox-box/url
      version: virtualbox-box/version

- name: aws-box
  serial: true
  plan:
  - aggregate:
    - get: final-release
      passed: [shipit]
      trigger: true
    - get: garden-linux-release
      passed: [shipit]
      resource: garden-linux
      trigger: true
    - get: concourse
      params: {submodules: none}
      passed: [shipit]
      trigger: true
    - get: concourse-lite
  - task: build-box
    privileged: true
    file: concourse-lite/ci/build-aws.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{aws-box-access-key}}
        AWS_SECRET_ACCESS_KEY: {{aws-box-secret-key}}
  - put: aws-box
    params: {from: build-box/concourse-lite/concourse-aws-ubuntu-trusty-(.*).box}
  - task: build-release-notes
    file: concourse/ci/build-release-notes.yml
  - put: aws-box-cloud
    params:
      description: build-release-notes/notes.md
      release: true
      url: aws-box/url
      version: aws-box/version

- name: push-docs
  serial: true
  plan:
  - aggregate:
    - get: version
      trigger: true
      passed: [shipit]
    - get: concourse
      params: {submodules: none}
      resource: concourse-develop
  - task: build
    file: concourse/ci/build-docs.yml
    config:
      params:
        ANALYTICS_ID: {{analytics-id}}
        VERSION_FILE: version/number
  - put: concourse-docs
    params:
      current_app_name: docs
      manifest: build/concourse/docs/manifest.yml

- name: push-departures
  serial: true
  plan:
  - get: departures
    trigger: true
  - put: departures-app
    params:
      current_app_name: departures
      manifest: departures/manifest.yml

- name: github-release
  plan:
  - aggregate:
    - get: final-release
      passed: [shipit]
      trigger: true
    - get: garden-linux
      passed: [shipit]
      trigger: true
    - get: concourse
      params: {submodules: none}
      passed: [shipit]
      trigger: true
    - get: concourse-master
      params: {submodules: none}
      passed: [shipit]
      trigger: true
  - aggregate:
    - task: build-release-notes
      file: concourse/ci/build-release-notes.yml
    - task: rename-release
      file: concourse/ci/rename-release.yml
    - task: generate-commitish
      config:
        platform: linux

        image: docker:///concourse/git-resource

        inputs:
        - name: concourse-master

        run:
          path: sh
          args:
          - -c
          - |
            git -C concourse-master rev-parse HEAD > commitish
  - put: github-release
    params:
      name: build-release-notes/release-name
      tag: build-release-notes/release-name
      body: build-release-notes/notes.md
      commitish: generate-commitish/commitish
      globs:
      - final-release/*.tgz
      - rename-release/garden-linux/garden-linux-*.tgz

- name: product
  serial: true
  plan:
  - aggregate:
    - get: p-concourse
      trigger: true
    - get: final-release
      passed: [shipit]
      trigger: true
    - get: garden-linux-release
      passed: [shipit]
      resource: garden-linux
      trigger: true
    - get: version
      trigger: true
      passed: [shipit]
  - task: build
    file: p-concourse/ci/build.yml
  - put: product
    params: {from: build/p-concourse/p-concourse-(.*).pivotal}

- name: hangar
  public: true
  plan:
  - get: hangar
    trigger: true
  - task: build
    file: hangar/build.yml

- name: publish-houdini
  plan:
  - get: houdini
    trigger: true
  - task: build-artifacts
    file: houdini/ci/build-artifacts.yml
  - put: houdini-artifacts
    params:
      name: build-artifacts/dist/release-name
      tag: build-artifacts/dist/release-name
      globs: [build-artifacts/dist/artifacts/*]

- name: master-merge
  plan:
    - aggregate:
      - get: concourse-master
        params: {submodules: none, fetch: [develop]}
        trigger: true
      - get: concourse # for build scripts
        params: {submodules: none}
    - task: merge-to-develop
      file: concourse/ci/master-merge.yml
    - put: concourse
      params:
        repository: merge-to-develop/concourse-master

- name: tracksuit
  serial: true
  plan:
  - get: periodic-tracksuit
    trigger: true
  - get: tracksuit
  - task: tracksuit
    file: tracksuit/run.yml
    config:
      params:
        GITHUB_TOKEN: {{tracksuit-github-token}}
        TRACKER_TOKEN: {{tracksuit-tracker-token}}
        PROJECT_ID: 1059262
        ORGANIZATION: concourse

resources:
- name: version
  type: semver
  source:
    bucket: concourse-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: final-release
  type: s3
  source:
    bucket: concourse-releases
    regexp: concourse-(.*).tgz
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: candidate-release
  type: s3
  source:
    bucket: concourse-release-candidates
    regexp: concourse-(.*).tgz
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: virtualbox-box
  type: s3
  source:
    bucket: concourse-boxes
    regexp: concourse-virtualbox-ubuntu-trusty-(.*).box
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: aws-box
  type: s3
  source:
    bucket: concourse-boxes
    regexp: concourse-aws-ubuntu-trusty-(.*).box
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: aws-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: {{bosh-deployment}}

- name: lite-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: concourse-testflight

- name: virtualbox-box-cloud
  type: vagrant-cloud
  source:
    username: concourse
    box: lite
    provider: virtualbox
    access_token: {{atlas-access-token}}

- name: aws-box-cloud
  type: vagrant-cloud
  source:
    username: concourse
    box: lite
    provider: aws
    access_token: {{atlas-access-token}}

- name: garden-linux
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release

- name: turbulence
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release

- name: tracker
  type: tracker
  source:
    tracker_url: https://www.pivotaltracker.com
    project_id: "1059262"
    token: {{tracker-token}}

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: concourse-lite
  type: git
  source:
    uri: https://github.com/concourse/concourse-lite.git
    branch: master

- name: concourse-develop
  type: git
  source:
    uri: https://github.com/concourse/concourse.git
    branch: develop

- name: concourse-docs
  type: cf
  source:
    api: {{cf-target}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

- name: departures
  type: git
  source:
    uri: https://github.com/vito/departure-board.git
    branch: master

- name: departures-app
  type: cf
  source:
    api: {{cf-target}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}

- name: github-release
  type: github-release
  source:
    access_token: {{concourse-github-release-access-token}}
    repository: concourse
    user: concourse

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: develop
    private_key: {{concourse-repo-private-key}}

- name: concourse-master
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: master
    private_key: {{concourse-repo-private-key}}

- name: bosh-lite
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-lite.git
    branch: master

- name: hangar
  type: git
  source:
    uri: https://github.com/concourse/hangar.git
    branch: master

- name: p-concourse
  type: git
  source:
    uri: https://github.com/concourse/p-concourse.git
    branch: master

- name: product
  type: s3
  source:
    bucket: concourse-product
    regexp: p-concourse-(.*).pivotal
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: {{deployments-repo-private-key}}

- name: houdini
  type: git
  source:
    uri: https://github.com/vito/houdini.git
    branch: master

- name: houdini-artifacts
  type: github-release
  source:
    user: vito
    repository: houdini
    access_token: {{houdini-github-release-access-token}}

- name: bosh-lites
  type: pool
  source:
    uri: git@github.com:concourse/locks.git
    branch: master
    pool: bosh-lites
    private_key: {{locks-repo-private-key}}

- name: tracksuit
  type: git
  source:
    uri: https://github.com/vito/tracksuit.git

- name: periodic-tracksuit
  type: time
  source:
    interval: 10m
